export default {

  HAS_LOGGED: 'HAS_LOGGED',
  REQUEST_ERROR: 'REQUEST_ERROR',
  COURSES_RETRIEVED: 'COURSES_RETRIEVED',
  COURSE_SELECTED: 'COURSE_SELECTED',
  COURSEWORKS_RETRIEVED: 'COURSEWORKS_RETRIEVED',
  SUBMISSIONS_RETRIEVED: 'SUBMISSIONS_RETRIEVED',
  HAS_COURSEWORKS: 'HAS_COURSEWORKS',
  GLOBAL_POINTS_CALCULATED: 'GLOBAL_POINTS_CALCULATED'

}
