export default {

  CHANGE_LOGIN_STATUS: 'CHANGE_LOGIN_STATUS',
  LOGIN_DATA_SAVED: 'LOGIN_DATA_SAVED',
  ACCESS_GRANTED: 'ACCESS_GRANTED',
  LOGOUT: 'LOGOUT',

  COURSES_LOADED: 'COURSES_LOADED',
  REQUEST_ERROR: 'REQUEST_ERROR',
  COURSES_RETRIEVED: 'COURSES_RETRIEVED',
  COURSE_SELECTED: 'COURSE_SELECTED',

  COURSE_WORKS_RETRIEVED: 'COURSE_WORKS_RETRIEVED',
  COURSE_WORKS_LOADED: 'COURSE_WORKS_LOADED',

  RESET_SUBMISSIONS: 'RESET_SUBMISSIONS',
  SUBMISSIONS_RETRIEVED: 'SUBMISSIONS_RETRIEVED',
  SUBMISSIONS_LOADED: 'SUBMISSIONS_LOADED',
  HAS_COURSE_WORKS: 'HAS_COURSE_WORKS',
  RESET_POINTS: 'RESET_POINTS',
  GLOBAL_POINTS_CALCULATED: 'GLOBAL_POINTS_CALCULATED'

}
