export default {

  IS_LOGGED: 'IS_LOGGED',
  ACCESS_GRANTED: 'ACCESS_GRANTED',
  COURSES_LOADED: 'COURSES_LOADED',
  REQUEST_ERROR: 'REQUEST_ERROR',
  COURSES_RETRIEVED: 'COURSES_RETRIEVED',
  COURSE_SELECTED: 'COURSE_SELECTED',
  COURSE_WORKS_RETRIEVED: 'COURSE_WORKS_RETRIEVED',
  COURSE_WORKS_LOADED: 'COURSE_WORKS_LOADED',
  SUBMISSIONS_RETRIEVED: 'SUBMISSIONS_RETRIEVED',
  SUBMISSIONS_LOADED: 'SUBMISSIONS_LOADED',
  HAS_COURSEWORKS: 'HAS_COURSEWORKS',
  GLOBAL_POINTS_CALCULATED: 'GLOBAL_POINTS_CALCULATED'

}
